# Generated by Django 3.2.5 on 2021-07-12 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('first_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyisim')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/authors/%Y/%m/%d/', verbose_name='Fotoğraf')),
                ('biography', models.TextField(verbose_name='Biyografi')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=150, verbose_name='İsim')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/book-covers/%Y/%m/%d/', verbose_name='Kapak Görseli')),
                ('page', models.PositiveIntegerField(blank=True, default=0, verbose_name='Sayfa Sayısı')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='book.author', verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
            },
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('language_name', models.CharField(max_length=50, verbose_name='Dil')),
                ('language_code', models.CharField(max_length=10, verbose_name='Dil Kodu')),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.CreateModel(
            name='BookLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
            ],
            options={
                'verbose_name': 'Seviye',
                'verbose_name_plural': 'Kitap Seviyeleri',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('description', models.CharField(max_length=256, verbose_name='Açıklama')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(editable=False, max_length=150)),
                ('content', models.TextField(verbose_name='Sayfa İçeriği')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sayfa Numarası')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/book-pages/%Y/%m/%d/', verbose_name='Görsel')),
                ('image_position', models.SmallIntegerField(blank=True, help_text="0, 1, 2 değerlerine izin verilmektedir. 0 değeri en üst 2 değeri ise en altı işaret eder.             İçerik Konumu'yla aynı olması durumunda görsel en arkaya gönderilir ve yazı görselin üzerine gelir. Boş bırakılırsa eğer                 sırasıyla ilk başta görsel eklenir ve altına da yazı alanı gelir.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Görselin Konumu')),
                ('content_position', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='İçeriğin Konumu')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_pages', to='book.book', verbose_name='Kitap')),
            ],
            options={
                'verbose_name': 'Kitap Sayfası',
                'verbose_name_plural': 'Kitap Sayfaları',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_books', to='book.category', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language_books', to='book.booklanguage', verbose_name='Kitap Dili'),
        ),
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_books', to='book.booklevel', verbose_name='Seviye'),
        ),
    ]
