# Generated by Django 3.2.5 on 2021-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_readinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='counter',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Okuma Sayacı'),
        ),
    ]
