# Generated by Django 3.2.5 on 2021-08-12 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_readinghistory_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklevel',
            name='title_english',
            field=models.CharField(default='English title', max_length=50, verbose_name='İngilizce Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_english',
            field=models.CharField(default='English description', max_length=256, verbose_name='İngilizce Açıklama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_english',
            field=models.CharField(default='English title', max_length=50, verbose_name='İngilizce Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='content_position',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Orta'), (1, 'Üst'), (2, 'Alt')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='İçeriğin Konumu'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='image_position',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Orta'), (1, 'Üst'), (2, 'Alt')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Görselin Konumu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Türkçe Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Türkçe Başlık'),
        ),
    ]
