# Generated by Django 3.2.5 on 2021-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210823_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'yazar', 'verbose_name_plural': 'yazarlar'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'kitap', 'verbose_name_plural': 'kitaplar'},
        ),
        migrations.AlterModelOptions(
            name='booklanguage',
            options={'verbose_name': 'dil', 'verbose_name_plural': 'diller'},
        ),
        migrations.AlterModelOptions(
            name='booklevel',
            options={'verbose_name': 'seviye', 'verbose_name_plural': 'kitap seviyeleri'},
        ),
        migrations.AlterModelOptions(
            name='bookpage',
            options={'verbose_name': 'kitap sayfası', 'verbose_name_plural': 'kitap sayfaları'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'verbose_name': 'okuma geçmişi', 'verbose_name_plural': 'okuma geçmişleri'},
        ),
        migrations.AlterField(
            model_name='booklanguage',
            name='language_code',
            field=models.CharField(help_text="Dil Kodu'nu <a href='http://www.lingoes.net/en/translator/langcode.htm'><strong>ISO Dil Kodları</strong></a> sayfasındaki kodlara uygun olarak giriniz. Bu kitap dinlerken okuyucunun tercüme dilini etkiliyor.", max_length=10, verbose_name='Dil Kodu'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Okuma Sayacı'),
        ),
    ]
