# Generated by Django 3.2.5 on 2021-07-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Sınav', 'verbose_name_plural': 'Sınavlar'},
        ),
    ]
