# Generated by Django 3.2.5 on 2021-07-29 15:41

import constants.quiz_strings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_instructorprofile'),
        ('quiz', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakingQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(default='-', editable=False, max_length=150, verbose_name='Başlık')),
                ('total_point', models.PositiveIntegerField(default=0, verbose_name='Toplam Puan')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_taking_quiz', to='account.childprofile', verbose_name='Çocuk')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz_taking_quiz', to='quiz.quiz', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Çözülmüş Sınav Kaydı',
                'verbose_name_plural': 'Çözülmüş Sınav Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='TakingQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('taking_quiz_title', models.TextField(blank=True, null=True, verbose_name='Girilen Sınav Başlığı')),
                ('question_text', models.TextField(blank=True, null=True, verbose_name='Soru')),
                ('question_topic_content', models.TextField(blank=True, null=True, verbose_name='Sorunun Konusu')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Cevap')),
                ('answer_is_correct', models.BooleanField(blank=True, null=True, verbose_name='Cevap Doğru Mu?')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_taking_quiz', to='quiz.answer', verbose_name=constants.quiz_strings.QuizStrings.TakingQuizAnswersStrings)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_taking_quiz', to='quiz.question', verbose_name='Soru')),
                ('taking_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_quizes', to='quiz.takingquiz', verbose_name='Girilen Sınav')),
            ],
            options={
                'verbose_name': 'Çözülmüş Sınav Kaydı',
                'verbose_name_plural': 'Çözülmüş Sınav Kayıtları',
            },
        ),
    ]
