# Generated by Django 3.2.5 on 2021-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210729_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takingquizanswer',
            name='answer_is_correct',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Cevap Doğru Mu?'),
        ),
        migrations.AlterField(
            model_name='takingquizanswer',
            name='answer_text',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Cevap'),
        ),
        migrations.AlterField(
            model_name='takingquizanswer',
            name='question_text',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Soru'),
        ),
        migrations.AlterField(
            model_name='takingquizanswer',
            name='question_topic_content',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Sorunun Konusu'),
        ),
        migrations.AlterField(
            model_name='takingquizanswer',
            name='taking_quiz_title',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Girilen Sınav Başlığı'),
        ),
    ]
