# Generated by Django 3.2.5 on 2021-07-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_auto_20210712_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=250, verbose_name='Şehirler')),
                ('address', models.CharField(max_length=250, verbose_name='Adres')),
                ('website', models.CharField(max_length=250, verbose_name='Web Adresi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_schools', to='country.city', verbose_name='Şehirler')),
            ],
            options={
                'verbose_name': 'Okul',
                'verbose_name_plural': 'Okullar',
            },
        ),
    ]
