# Generated by Django 3.2.5 on 2021-07-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_instructorprofile'),
        ('school', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_school2', to='account.instructorprofile', verbose_name='Eğitmen'),
        ),
    ]
