# Generated by Django 3.2.5 on 2021-07-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_instructorprofile'),
        ('school', '0006_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_list_children', to='account.childprofile', verbose_name='Öğrenci/Çocuk'),
        ),
    ]
