# Generated by Django 3.2.5 on 2021-08-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_studentlist_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_list_class', to='school.class', verbose_name='Sınıf'),
        ),
    ]
