# Generated by Django 3.2.5 on 2021-09-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_studentlist_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name', 'grade'], 'verbose_name': 'sınıf', 'verbose_name_plural': 'sınıflar'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'okul', 'verbose_name_plural': 'okullar'},
        ),
        migrations.AlterModelOptions(
            name='studentlist',
            options={'verbose_name': 'sınıf öğrencisi', 'verbose_name_plural': 'sınıf öğrencileri'},
        ),
    ]
