# Generated by Django 3.2.5 on 2021-09-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20210816_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'şehir', 'verbose_name_plural': 'şehirler'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'ülke', 'verbose_name_plural': 'ülkeler'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'bölge', 'verbose_name_plural': 'bölgeler'},
        ),
        migrations.AlterField(
            model_name='city',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district_cities', to='country.district', verbose_name='Bölge'),
            preserve_default=False,
        ),
    ]
