# Generated by Django 3.2.5 on 2021-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210712_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Kimlik Numarası'),
        ),
    ]
