# Generated by Django 3.2.5 on 2021-07-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210713_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email', 'username', 'identity_number')},
        ),
    ]
