# Generated by Django 3.2.5 on 2021-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
    ]
