# Generated by Django 3.2.5 on 2021-07-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210713_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childlist',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_list', to='account.childprofile', verbose_name='Çocuk'),
        ),
    ]
