# Generated by Django 3.2.5 on 2021-07-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('account', '0008_auto_20210714_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_instructor', serialize=False, to='account.customuser', verbose_name='Kullanıcı')),
                ('branch', models.CharField(max_length=50, verbose_name='Branş')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_instructor', to='school.school', verbose_name='Okul')),
            ],
            options={
                'verbose_name': 'Eğitmen',
                'verbose_name_plural': 'Eğitmenler',
            },
        ),
    ]
