from .country_serializers import CountrySerializer, CountryDetailWithCitySerializer
from .city_serializers import CitySerializer, CityDetailWithCountrySerializer
from .district_serializers import DistrictSerializer